arm:
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
      joints:
        - s1j
        - s2j
        - s3j
        - ej
        - rollj
        - pitchj
        - yawj
  manipulator_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
    gains:
    gains:
      s1j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      s2j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      s3j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      ej:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      rollj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      pitchj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      yawj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  pos_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
    gains:
      s1j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      s2j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      s3j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      ej:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      rollj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      pitchj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      yawj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        s1j: {trajectory: 0.1, goal: 0.1}
        s2j: {trajectory: 0.1, goal: 0.1}
        s3j: {trajectory: 0.1, goal: 0.1}
        ej: {trajectory: 0.1, goal: 0.1}
        rollj: {trajectory: 0.1, goal: 0.1}
        pitchj: {trajectory: 0.1, goal: 0.1}
        yawj: {trajectory: 0.1, goal: 0.1}
  vel_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
    gains:
      s1j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      s2j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      s3j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      ej:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      rollj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      pitchj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      yawj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  joint_group_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
    #J1:
    #  pid: {p: 100.0, i: 1, d: 1.0}
    #J2:
    #  pid: {p: 100.0, i: 1, d: 1.0}
    #J3:
    #  pid: {p: 100.0, i: 1, d: 1.0}
    #J4:
    #  pid: {p: 100.0, i: 1, d: 1.0}
    #J5:
    #  pid: {p: 100.0, i: 1, d: 1.0}
    #J6:
    #  pid: {p: 100.0, i: 1, d: 1.0}
  arm_position_controller:
    type: pos_vel_acc_controllers/JointTrajectoryController
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
    gains:
      s1j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      s2j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      s3j:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      ej:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      rollj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      pitchj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      yawj:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
    constraints:
#      goal_time: 10.0                  # Override default
      stopped_velocity_tolerance: 0
      s1j:
        goal: 3.14 #0.05 # 3 degree
        trajectory: 3.14 #0.1 # 6 degree
      s2j:
        goal: 3.14 #0.05 # 3 degree
        trajectory: 3.14 #0.1 # 6 degree
      s3j:
        goal: 3.14 #0.05 # 3 degree
        trajectory: 3.14 #0.1 # 6 degree
      ej:
        goal: 3.14 #0.2 # 12 degree
        trajectory: 3.14 #0.25 # 15 degree
      rollj:
        goal: 3.14 #0.1 # 6 degree
        trajectory: 3.14 #0.1 # 6 degree
      pitchj:
        goal: 3.14 #0.1 # 6 degree
        trajectory: 3.14 #0.1 # 6 degree
      yawj:
        goal: 3.14 #0.2 # 12 degree
        trajectory: 3.14 #0.5 # 30 degree

    state_publish_rate:  50            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

controller_list:
  - name: arm/pos_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
