controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
  - name: fake_SoftHand_research_controller
    type: $(arg fake_execution_type)
    joints:
      - qbhand_synergy_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: home
  - group: SoftHand_research
    pose: open