controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
  - name: SoftHand_research_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - qbhand_synergy_joint
  - name: vel_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj